perpus/urls.py
from django.urls import path
# from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('daftar-buku/', views.BukuListView.as_view(), name="daftar_buku"),
    path('daftar-anggota/', views.AnggotaListView.as_view(), name="daftar_anggota"),
    path('create-buku/', views.CreateBukuView.as_view(), name="create_buku"),
    path('edit-buku/<int:pk>/', views.EditBukuView.as_view(), name="edit_buku"),
    path('hapus-buku/<int:id_buku>/', views.hapus_buku, name="hapus_buku"),
    path('create-anggota/', views.CreateAnggotaView.as_view(), name="create_anggota"),
    path('edit-anggota/<int:pk>/', views.EditAnggotaView.as_view(), name="edit_anggota"),
    path('hapus-anggota/<int:id_anggota>/', views.hapus_anggota, name="hapus_anggota"),
    path('peminjaman-buku/', views.CreatePeminjamanView.as_view(), name="minjem"),
    path('pengembalian-buku/', views.CreatePengembalianView.as_view(), name="kembali"),
    path("history-peminjaman/", views.history_minjem, name="history_minjem"),
    path("history-pengembalian/", views.history_kembali, name="history_kembali"),
]

perpus_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perpus.urls')),
    path('members/', include("django.contrib.auth.urls")),
    path('members/', include('members.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perpus/models.py
from django.db import models
from datetime import date

kelamin_list = (
	("L", "Laki-laki"),
	("P", "Perempuan"),
)

# Create your models here.
class Anggota(models.Model):
	nim = models.IntegerField()
	nama = models.CharField(max_length=255)
	jenis_kelamin = models.CharField(max_length=255, choices=kelamin_list)
	kelas = models.CharField(max_length=255)
	foto = models.ImageField(null=True, blank=True, upload_to="images/orang")

	def __str__(self):
		return self.nama

class Buku(models.Model):
	kode_buku = models.IntegerField()
	judul_buku = models.CharField(max_length=255)
	pengarang = models.CharField(max_length=255)
	klasifikasi = models.TextField(max_length=255)
	foto_buku = models.ImageField(null=True, blank=True, upload_to="images/buku")

	def __str__(self):
		return "%s - %s" % (self.judul_buku, self.pengarang)

class Peminjaman(models.Model):
	no_transaksi = models.IntegerField()
	tgl_pinjam = models.DateField()
	tgl_kembali = models.DateField()
	orang = models.OneToOneField(Anggota, on_delete=models.CASCADE)
	buku = models.ManyToManyField(Buku, related_name='buku_pinjam')

	def __str__(self):
		return f"{str(self.no_transaksi)} - Peminjam {self.orang.nama}"

class Pengembalian(models.Model):
	minjem_transaksi = models.OneToOneField(Peminjaman, on_delete=models.CASCADE)
	is_denda = models.BooleanField(default=False)
	nominal_denda = models.IntegerField(null=True,blank=True)

	def __str__(self):
		return f"Tgl Kembali {str(self.minjem_transaksi.tgl_kembali)} no transaksi {str(self.minjem_transaksi.no_transaksi)}"

perpus/forms.py
from django import forms
from .models import Buku, Anggota, Peminjaman, Pengembalian

class BukuForm(forms.ModelForm):
	class Meta:
		model = Buku
		fields = ('kode_buku', 'judul_buku', 'pengarang', 'klasifikasi', 'foto_buku')
		widgets = {
			'kode_buku': forms.NumberInput(attrs={'class': 'form-control'}),
			'judul_buku': forms.TextInput(attrs={'class': 'form-control'}),
			'pengarang': forms.TextInput(attrs={'class': 'form-control'}),
			'klasifikasi': forms.Textarea(attrs={'class': 'form-control'}),
			# 'foto_buku': forms.FileInput(attrs={'class': 'form-control'}),
		}


class AnggotaForm(forms.ModelForm):
	class Meta:
		model = Anggota
		fields = ('nim', 'nama', 'jenis_kelamin', 'kelas', 'foto')
		widgets = {
			'nim': forms.NumberInput(attrs={'class': 'form-control'}),
			'nama': forms.TextInput(attrs={'class': 'form-control'}),
			'jenis_kelamin': forms.Select(attrs={'class': 'form-control'}),
			'kelas': forms.TextInput(attrs={'class': 'form-control'}),
			# 'foto_buku': forms.FileInput(attrs={'class': 'form-control'}),
		}


class PeminjamanForm(forms.ModelForm):
	class Meta:
		model = Peminjaman
		fields = ('no_transaksi', 'tgl_pinjam', 'tgl_kembali', 'orang', 'buku')
		widgets = {
			'no_transaksi': forms.NumberInput(attrs={'class': 'form-control'}),
			'tgl_pinjam': forms.TextInput(attrs={'class': 'form-control', 'type':'date'}),
			'tgl_kembali': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
			'orang': forms.Select(attrs={'class': 'form-control'}),
			# 'buku': forms.Select(attrs={'class': 'form-control', 'multiple': True}),
		}


class PengembalianForm(forms.ModelForm):
	class Meta: 
		model = Pengembalian
		fields = ('minjem_transaksi', 'is_denda', 'nominal_denda')
		widgets = {
			'minjem_transaksi': forms.Select(attrs={'class': 'form-control'}),
			'nominal_denda': forms.NumberInput(attrs={'class': 'form-control'}),
		}


class EditAnggotaForm(forms.ModelForm):
	class Meta:
		model = Anggota
		fields = ('nim', 'nama', 'jenis_kelamin', 'kelas', 'foto')
		widgets = {
			'nim': forms.NumberInput(attrs={'class': 'form-control'}),
			'nama': forms.TextInput(attrs={'class': 'form-control'}),
			'jenis_kelamin': forms.Select(attrs={'class': 'form-control'}),
			'kelas': forms.TextInput(attrs={'class': 'form-control'}),
			# 'foto_buku': forms.FileInput(attrs={'class': 'form-control'}),
		}


class EditBukuForm(forms.ModelForm):
	class Meta:
		model = Buku
		fields = ('kode_buku', 'judul_buku', 'pengarang', 'klasifikasi', 'foto_buku')
		widgets = {
			'kode_buku': forms.NumberInput(attrs={'class': 'form-control'}),
			'judul_buku': forms.TextInput(attrs={'class': 'form-control'}),
			'pengarang': forms.TextInput(attrs={'class': 'form-control'}),
			'klasifikasi': forms.Textarea(attrs={'class': 'form-control'}),
			# 'foto_buku': forms.FileInput(attrs={'class': 'form-control'}),
		}

perpus/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from django.views.generic import ListView, CreateView, UpdateView
from django.http import HttpResponse, HttpResponseRedirect

from .authenticated import user_is_authenticated
from .models import Anggota, Buku, Peminjaman, Pengembalian
from .forms import EditBukuForm, EditAnggotaForm, BukuForm, AnggotaForm, PeminjamanForm, PengembalianForm
# Create your views here.
def home(req):
	if user_is_authenticated(req):
		return render(req, "home.html", {
			'total_anggota': Anggota.objects.all().count(),
			'total_buku': Buku.objects.all().count(),
			'total_pengembalian': Pengembalian.objects.all().count(),
			'total_peminjaman': Peminjaman.objects.all().count()})
	return HttpResponseRedirect(reverse('login'))

def history_minjem(req):
	if user_is_authenticated(req):
		list_minjem = Peminjaman.objects.all()
		paginator = Paginator(list_minjem, 4)
		page_number = req.GET.get('page')
		page_obj = paginator.get_page(page_number)
		if req.method == 'POST':
			if req.POST.get('cari_data'):
				start = req.POST.get('start')
				end = req.POST.get('end')
				list_minjem = Peminjaman.objects.filter(tgl_pinjam__gte=start, tgl_kembali__lte=end)
				paginator = Paginator(list_minjem, 4)
				page_number = req.GET.get('page')
				page_obj = paginator.get_page(page_number)
				return render(req, 'history_minjem.html', {'page_obj': page_obj})
		return render(req, 'history_minjem.html', {'page_obj': page_obj})
	return HttpResponseRedirect(reverse('login'))


def history_kembali(req):
	if user_is_authenticated(req):
		list_kembali = Pengembalian.objects.all()
		paginator = Paginator(list_kembali, 4)
		page_number = req.GET.get('page')
		page_obj = paginator.get_page(page_number)
		return render(req, 'history_kembali.html', {'page_obj': page_obj})
	return HttpResponseRedirect(reverse('login'))

def hapus_anggota(req, id_anggota):
	if user_is_authenticated(req):
		if req.method == 'POST':
			deleted_anggota = get_object_or_404(Anggota, id=id_anggota)
			if deleted_anggota.foto:
				deleted_anggota.foto.delete()
			deleted_anggota.delete()
		return HttpResponseRedirect(reverse('daftar_anggota'))
	return HttpResponseRedirect(reverse('login'))

def hapus_buku(req, id_buku):
	if user_is_authenticated(req):
		if req.method == 'POST':
			deleted_buku = get_object_or_404(Buku, id=id_buku)
			if deleted_buku.foto_buku:
				deleted_buku.foto_buku.delete()
			deleted_buku.delete()
		return HttpResponseRedirect(reverse('daftar_buku'))
	return HttpResponseRedirect(reverse('login'))

class BukuListView(ListView):
	paginate_by = 4
	model = Buku
	template_name = 'buku.html'


class AnggotaListView(ListView):
	paginate_by = 4
	model = Anggota
	template_name = 'anggota.html'


class CreatePeminjamanView(CreateView):
	model = Peminjaman
	form_class = PeminjamanForm
	template_name = 'add_minjem.html'
	success_url = reverse_lazy('home')


class CreatePengembalianView(CreateView):
	model = Pengembalian
	form_class = PengembalianForm
	template_name = 'add_kembali.html'
	success_url = reverse_lazy('home')


class CreateBukuView(CreateView):
	model = Buku
	form_class = BukuForm
	template_name = 'add_buku.html'
	success_url = reverse_lazy('daftar_buku')


class CreateAnggotaView(CreateView):
	model = Anggota
	form_class = AnggotaForm
	template_name = 'add_anggota.html'
	success_url = reverse_lazy('daftar_anggota')

class EditAnggotaView(UpdateView):
	model = Anggota
	form_class = EditAnggotaForm
	template_name = 'edit_anggota.html'
	success_url = reverse_lazy('daftar_anggota')

	def post(self, request, pk):
		if 'hapus' in self.request.POST:
			del_old_img = get_object_or_404(Anggota, pk=pk)
			if del_old_img.foto:
				del_old_img.foto.delete()
		return super(EditAnggotaView, self).post(request, pk)


class EditBukuView(UpdateView):
	model = Buku
	form_class = EditBukuForm
	template_name = 'edit_buku.html'
	success_url = reverse_lazy('daftar_buku')

	def post(self, request, pk):
		if 'hapus' in self.request.POST:
			del_old_img = get_object_or_404(Buku, pk=pk)
			if del_old_img.foto_buku:
				del_old_img.foto_buku.delete()
		return super(EditBukuView, self).post(request, pk)

perpus/templates/add_anggota.html
{% extends 'base.html' %}
{% block title %}Tambah Anggota{% endblock %}
{% block content %}
	<div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Tambah Anggota</h3>
              </div>
              <form method="post" enctype="multipart/form-data">
                <div class="card-body">
              	{% csrf_token %}
                {{form.as_p}}
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </form>
            </div>
{% endblock %}

perpus/templates/add_buku.html
{% extends 'base.html' %}
{% block title %}Tambah Buku{% endblock %}
{% block content %}
	<div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Tambah Buku</h3>
              </div>
              <form method="post" enctype="multipart/form-data">
                <div class="card-body">
              	{% csrf_token %}
                {{form.as_p}}
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Submit</button>
                </div>
              </form>
            </div>
            <script>
                let buku_el = document.getElementById('id_kode_buku');
                let d = new Date();
                buku_el.value = d.getMilliseconds();
            </script>
{% endblock %}

perpus/templates/add_kembali.html
{% extends 'base.html' %}
{% block title %}Pengembalian Buku{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    	<div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title">Mengembalikan Buku</h3>
                  </div>
                  <form method="post">
                    <div class="card-body">
                  	{% csrf_token %}
                    {{form.as_p}}
                    </div>
                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                </div>
{% else %}
    <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

          <p>
            Untuk melihat halaman ini anda harus <a href="{% url 'login' %}">login</a> terlebih dahulu
          </p>
        </div>
        <!-- /.error-content -->
      </div>
{% endif %}
{% endblock %}

perpus/templates/add_minjem.html
{% extends 'base.html' %}
{% block title %}Peminjaman Buku{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <div class="row">
    		<div class="col-md">
    			<div class="card card-warning">
                  <div class="card-header">
                    <h3 class="card-title">Pinjam Buku</h3>
                  </div>
                  <form method="post">
                    <div class="card-body">
                    {% csrf_token %}
                  	{{form}}
                    </div>
                    <div class="card-footer">
                      <button type="submit" class="btn btn-warning">Submit</button>
                    </div>
                  </form>
                </div>
    		</div>
    </div>
      <script>
        let select_buku = document.getElementById('id_buku');
          let d = new Date();
          let no_transaksi = document.getElementById('id_no_transaksi');
          no_transaksi.value = parseInt(d.getFullYear().toString() + d.getDate().toString() + d.getMonth().toString() + d.getMilliseconds().toString());

          select_buku.classList.add('form-control');
      </script>
{% else %}
    <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

          <p>
            Untuk melihat halaman ini anda harus <a href="{% url 'login' %}">login</a> terlebih dahulu
          </p>
        </div>
        <!-- /.error-content -->
      </div>
{% endif %}
{% endblock %}

perpus/templates/anggota.html
{% extends 'base.html' %}
{% block title %}Anggota{% endblock %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
  <a href="{% url 'create_anggota' %}" class="btn btn-success mb-3">Tambah Anggota</a>
  	<div class="card">
                <div class="card-header">
                  <h3 class="card-title">Daftar Anggota</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>NIM</th>
                        <th>Foto</th>
                        <th>Nama</th>
                        <th>Jenis Kelamin</th>
                        <th>Kelas</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                    	{% for orang in object_list %}
  	                    <tr>
                          <td>{{orang.nim}}</td>
  	                      <td>
                          {% if orang.foto %}
                              <img src="{{orang.foto.url}}" alt="gambar_buku" width="100" height="100" />
                          {% else %}
                              {% if orang.jenis_kelamin == "L" %}
                                <img src="{% static 'perpus/default/face_man.png' %}" alt="gambar_buku" width="100" height="100" />
                              {% else %}
                                <img src="{% static 'perpus/default/face_woman.png' %}" alt="gambar_buku" width="100" height="100" />
                              {% endif %}
                          {% endif %}
                          </td>
                           <td>{{orang.nama}}</td>
                           <td>{{orang.jenis_kelamin}}</td>
                           <td>{{orang.kelas}}</td>
                           <td>
                            <div class="d-flex justify-content-around">
                                <a href='{% url "edit_anggota" orang.pk %}' class="btn btn-success"><i class="fas fa-edit"></i></a>
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#id{{orang.id}}">
                                  <i class="fas fa-trash"></i>
                                </button>
                                <div class="modal fade" id="id{{orang.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title text-bold" id="exampleModalLabel">Peringatan</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                      <h5>Apakah kamu yakin ingin menghapus data ini?</h5>
                                    </div>
                                    <div class="modal-footer">
                                      <form method="post" action="{% url 'hapus_anggota' orang.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                      </form>
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                           </td>
  	                    </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
               <div class="card-footer clearfix">
                  <ul class="pagination pagination-sm m-0 float-right">
                    {% if page_obj.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">«</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">»</a></li>
                    {% endif %}
                  </ul>
                </div>
              </div>
{% else %}
    <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

          <p>
            Untuk melihat halaman ini anda harus <a href="{% url 'login' %}">login</a> terlebih dahulu
          </p>
        </div>
        <!-- /.error-content -->
      </div>
{% endif %}
{% endblock %}

perpus/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Perpus app {% endblock %}</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'perpus/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'perpus/dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home' %}" class="nav-link">Home</a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a class="brand-link">
      <span class="brand-text font-weight-light">Perpus app</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">Admin</a>
        </div>
      </div>


      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="{% url 'daftar_anggota' %}" class="nav-link">
              <i class="fas fa-users"></i>
              <p>
                Anggota
              </p>
            </a>
          </li>
           <li class="nav-item">
            <a href="{% url 'daftar_buku' %}" class="nav-link">
              <i class="fas fa-book"></i>
              <p>
                Buku
              </p>
            </a>
          </li>
           <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-table"></i>
              <p>
                Transaksi
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'minjem' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Peminjaman</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'kembali' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Pengembalian</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-history"></i>
              <p>
                History
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'history_minjem' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Laporan Peminjaman</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'history_kembali' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Laporan Pengembalian</p>
                </a>
              </li>
            </ul>
          </li>
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="fas fa-user"></i>
                  <p>
                    User Controls
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'profile' user.pk %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Detail User</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'password' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Ganti Password</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">
                  <i class="fas fa-sign-out-alt"></i>
                  <p>
                    Logout
                  </p>
                </a>
              </li>
          {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md">
            <h1>Pinjam Buku Perpus SMK Negeri 10 Pepega</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      {% block content %} {% endblock %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="https://adminlte.io">Aji Mustofa</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<!-- jQuery -->
<script src="{% static 'perpus/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'perpus/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'perpus/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'perpus/dist/js/demo.js' %}"></script>
</body>
</html>

perpus/templates/edit_anggota.html
{% extends 'base.html' %}
{% block title %}Edit Anggota{% endblock %}
{% block content %}
	<div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Edit Anggota</h3>
              </div>
              <form method="post" enctype="multipart/form-data">
                <div class="card-body">
              	{% csrf_token %}
                {{form.as_p}}
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Update</button>
                  <button name='hapus' value='delete' type="submit" class="btn btn-success">Update and Change Photo</button>
                </div>
              </form>
            </div>
            <script>
                let body_card = document.querySelector('.card-body');
                let  img_url = document.querySelector('label[for="id_foto"]').nextSibling.nextSibling.getAttribute('href');
                let img = document.createElement('img');
                img.setAttribute('src', img_url);
                img.setAttribute('width', 150);
                img.setAttribute('height', 150);
                body_card.appendChild(img);
            </script>
{% endblock %}

perpus/templates/edit_buku.html
{% extends 'base.html' %}
{% block title %}Edit Buku{% endblock %}
{% block content %}
	<div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Edit Buku</h3>
              </div>
              <form method="post" enctype="multipart/form-data">
                <div class="card-body">
              	{% csrf_token %}
                {{form.as_p}}
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Update</button>
                  <button name='hapus' value='delete' type="submit" class="btn btn-info">Update and Change Photo</button>
                </div>
              </form>
            </div>
            <script>
                let body_card = document.querySelector('.card-body');
                let  img_url = document.querySelector('label[for="id_foto_buku"]').nextSibling.nextSibling.getAttribute('href');
                let img = document.createElement('img');
                img.setAttribute('src', img_url);
                img.setAttribute('width', 150);
                img.setAttribute('height', 150);
                body_card.appendChild(img);
            </script>
{% endblock %}